-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 18:05:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trinitydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trinitydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trinitydb` DEFAULT CHARACTER SET utf8 ;
USE `trinitydb` ;

-- -----------------------------------------------------
-- Table `trinitydb`.`AstaBustaChiusa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trinitydb`.`AstaBustaChiusa` (
  `idAstaBustaChiusa` INT NOT NULL,
  `baseAsta` INT NOT NULL,
  `durata` DATE NOT NULL,
  `oggetto` VARCHAR(45) NOT NULL,
  `venditore` INT NOT NULL,
  `offerta` INT NOT NULL,
  `stato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAstaBustaChiusa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trinitydb`.`AstaSuperamentoImmediato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trinitydb`.`AstaSuperamentoImmediato` (
  `idAstaSuperamentoImmediato` INT NOT NULL,
  `baseAsta` INT NOT NULL,
  `durata` DATE NOT NULL,
  `oggetto` VARCHAR(45) NOT NULL,
  `timeSlot` DATE NOT NULL,
  `offerta` INT NOT NULL,
  `idUtente` INT NULL,
  PRIMARY KEY (`idAstaSuperamentoImmediato`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
